5) Data Analytics II
1. Implement logistic regression using Python/R to perform classification on 
Social_Network_Ads.csv dataset.
2. Compute Confusion matrix to find TP, FP, TN, FN, Accuracy, Error rate, Precision, Recall
on the given dataset.

In [30]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [31]:
df = pd.read_csv('Social_Network_Ads.csv')
df

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [32]:
df.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [33]:
df.columns

Index(['User ID', 'Gender', 'Age', 'EstimatedSalary', 'Purchased'], dtype='object')

In [34]:
df.isnull().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [35]:
numeric_columns = df.select_dtypes(include=np.number)
covariance_matrix = numeric_columns.cov()


In [36]:
most_promising_features = covariance_matrix.index[covariance_matrix.abs().sum().argsort()[::-1]]

In [37]:
print(most_promising_features)

Index(['User ID', 'EstimatedSalary', 'Age', 'Purchased'], dtype='object')


In [38]:
X = df.drop('EstimatedSalary', axis=1)

In [39]:
Y = df['Age']

In [40]:
print(X.head())

    User ID  Gender  Age  Purchased
0  15624510    Male   19          0
1  15810944    Male   35          0
2  15668575  Female   26          0
3  15603246  Female   27          0
4  15804002    Male   19          0


In [41]:
print(Y.head())

0    19
1    35
2    26
3    27
4    19
Name: Age, dtype: int64


In [42]:
from sklearn.model_selection import train_test_split


In [43]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [44]:
from sklearn.preprocessing import StandardScaler

In [45]:
scaler = StandardScaler()

In [46]:
from sklearn.preprocessing import LabelEncoder

# Initialize LabelEncoder
label_encoder = LabelEncoder()

# Apply label encoding to the 'Gender' column in X_train
X_train['Gender'] = label_encoder.fit_transform(X_train['Gender'])

# Now you can proceed with scaling
X_train_scaled = scaler.fit_transform(X_train)



In [47]:
# Apply label encoding to the 'Gender' column in X_test using the same label encoder
X_test['Gender'] = label_encoder.transform(X_test['Gender'])

# Now you can proceed with scaling
X_test_scaled = scaler.transform(X_test)


In [48]:
X_test_scaled

array([[ 0.11630156, -1.        ,  0.79753468, -0.74898305],
       [-1.10486346, -1.        ,  2.07309956,  1.3351437 ],
       [ 1.21993527, -1.        , -0.96863208, -0.74898305],
       [ 0.49358178, -1.        ,  0.99377543,  1.3351437 ],
       [ 0.14218461, -1.        , -0.87051171, -0.74898305],
       [ 1.5250491 , -1.        , -0.77239133, -0.74898305],
       [-0.68868909, -1.        ,  0.89565505,  1.3351437 ],
       [ 1.36270951, -1.        , -0.87051171, -0.74898305],
       [ 0.4526142 ,  1.        ,  0.20881242, -0.74898305],
       [-1.08911099,  1.        ,  0.40505317, -0.74898305],
       [ 0.53219762, -1.        , -0.28178945, -0.74898305],
       [ 1.24911632, -1.        ,  1.4843773 ,  1.3351437 ],
       [ 1.20364008, -1.        , -1.45923396, -0.74898305],
       [-1.3058189 , -1.        , -1.75359508, -0.74898305],
       [ 0.50922294,  1.        , -0.77239133, -0.74898305],
       [ 1.16517732,  1.        , -0.28178945, -0.74898305],
       [-1.05831572, -1.

In [49]:
X_train_scaled

array([[-1.19424348, -1.        , -1.06675246, -0.74898305],
       [ 0.21592346,  1.        ,  0.79753468,  1.3351437 ],
       [ 0.64683448, -1.        ,  0.11069205,  1.3351437 ],
       ...,
       [-0.11569962, -1.        ,  0.50317355, -0.74898305],
       [-1.52869143,  1.        ,  0.11069205, -0.74898305],
       [-1.45447944, -1.        , -0.57615058, -0.74898305]])

In [50]:
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

# Initialize the scaler
scaler = StandardScaler()

# Fit and transform the training data
X_train_scaled = scaler.fit_transform(X_train)

# Transform the testing data
X_test_scaled = scaler.transform(X_test)

# Initialize and fit the logistic regression model
logreg = LogisticRegression()
logreg.fit(X_train_scaled, Y_train)

# Predict using the fitted model
y_pred = logreg.predict(X_test_scaled)



In [51]:
logreg = LogisticRegression(max_iter=1000)


In [52]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

logreg = LogisticRegression()
logreg.fit(X_train_scaled, Y_train)

Y_train_pred = logreg.predict(X_train_scaled)
Y_test_pred = logreg.predict(X_test_scaled)


In [53]:
logreg = LogisticRegression(solver='saga')


In [54]:
import warnings
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.exceptions import UndefinedMetricWarning

# Ignore the warning messages
warnings.filterwarnings("ignore", category=UndefinedMetricWarning)

# Calculate accuracy for training set
train_accuracy = accuracy_score(Y_train, Y_train_pred)

# Calculate accuracy for testing set
test_accuracy = accuracy_score(Y_test, y_pred)

# Calculate precision for training set
train_precision = precision_score(Y_train, Y_train_pred, average='weighted', zero_division=1)

# Calculate precision for testing set
test_precision = precision_score(Y_test, y_pred, average='weighted', zero_division=1)

# Calculate recall for training set
train_recall = recall_score(Y_train, Y_train_pred, average='weighted', zero_division=1)

# Calculate recall for testing set
test_recall = recall_score(Y_test, y_pred, average='weighted', zero_division=1)

# Calculate F1 score for training set
train_f1_score = f1_score(Y_train, Y_train_pred, average='weighted', zero_division=1)

# Calculate F1 score for testing set
test_f1_score = f1_score(Y_test, y_pred, average='weighted', zero_division=1)


In [55]:
from sklearn.metrics import precision_score, recall_score, f1_score

# Calculate precision
precision = precision_score(Y_test, y_pred, average='micro')

# Calculate recall
recall = recall_score(Y_test, y_pred, average='micro')

# Calculate F1 score
f1_score = f1_score(Y_test, y_pred, average='micro')



In [56]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(Y_test, y_pred)


In [58]:
cm

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 2, 0, 0],
       [0, 0, 0, ..., 0, 0, 1]], dtype=int64)